language: java

env:
  global:
    - JDK_URL=http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jdk-8u45-linux-x64.tar.gz
    - JDK_HOME=jdk1.8.0_45
    - PATH==${JDK_HOME}/bin:${PATH}

before_script:
  - curl -v -j -k -L -H "Cookie: oraclelicense=accept-securebackup-cookie" ${JDK_URL} | tar xv

script:
  - bash jcompilo.sh
