version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "build/build.dependencies" }}
          - v2-dependencies-

      - run: 
          name: Update Libraries
          command: ./jcompilo.sh update || true

      - save_cache:
          paths:
            - ~/repo/lib
          key: v2-dependencies-{{ checksum "build/build.dependencies" }}

      - run: 
          name: Compile, Test and Package
          command: ./jcompilo.sh
      
      - store_test_results:
          path: ~/repo/build/artifacts/reports/
          
      - store_artifacts:
          path: ~/repo/build/artifacts/ 
