version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "build/build.dependencies" }}
          - v2-dependencies-

      - run: ./jcompilo.sh update || true

      - save_cache:
          paths:
            - ~/repo/lib
          key: v2-dependencies-{{ checksum "build/build.dependencies" }}

      - run: ./jcompilo.sh
